# Generated by Django 4.1.1 on 2022-09-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
