# Generated by Django 4.1.1 on 2022-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0002_rename_password_userdetails_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='password2',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
